name = "FFTInterpolations"
uuid = "e9c4abe8-3893-4664-acb8-58f49d1e9fc0"
authors = ["roflmaostc <fxw+git@mailbox.org>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1.2, 1.3"
julia = "1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"


[targets]
test = ["Test", "Random", "GeneralizedGenerated", "FFTW"]
